# Generated by Django 4.0.5 on 2022-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservemodel_number_of_guestss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservemodel',
            name='number_of_guestss',
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='time',
            field=models.CharField(choices=[('TIME', 'Time'), ('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default='TIME', max_length=10, verbose_name='Time'),
        ),
    ]
