# Generated by Django 4.0.5 on 2022-07-11 21:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_reservemodel_number_of_guestss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name and surname')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('fb_link', models.URLField(verbose_name='Facebook link')),
                ('tw_link', models.URLField(verbose_name='Twitter link')),
                ('inst_link', models.URLField(verbose_name='Instagram link')),
                ('image', models.ImageField(upload_to=main.models.chef_directory_path, verbose_name='Image')),
            ],
        ),
    ]
