# Generated by Django 4.0.5 on 2022-07-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chefsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefsmodel',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
    ]
