# Generated by Django 4.0.5 on 2022-07-12 09:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chefsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the dish')),
                ('description', models.CharField(max_length=40, verbose_name='Position')),
                ('price', models.FloatField(verbose_name='Price')),
                ('image', models.ImageField(upload_to=main.models.dishes_directory_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
