# Generated by Django 4.0.5 on 2022-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dishesmodel_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesmodel',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Desription'),
        ),
    ]
