# Generated by Django 4.0.5 on 2022-07-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
