# Generated by Django 4.0.5 on 2022-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishesmodel',
            old_name='tab',
            new_name='tabs',
        ),
    ]
