# Generated by Django 4.0.5 on 2022-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_tab_dishesmodel_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
    ]
