# Generated by Django 4.0.5 on 2022-07-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
                ('number_of_guests', models.IntegerField(verbose_name='Number of guests')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
